<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="invoisys.SDK.Queue" Version="1.7.7" />
    <PackageReference Include="invoisys.SDK.Storage" Version="1.8.2" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.9" />
    <PackageReference Include="Serilog" Version="4.2.0" />
  </ItemGroup>

</Project>
